# https://supabase.com/docs/guides/cli/config
project_id = "heuyorrfwofteprzbxos"

[functions.email-sync]
verify_jwt = true

[functions.email-send]
verify_jwt = true

[functions.email-delete]
verify_jwt = true

[functions.email-classify]
verify_jwt = true
